language: php

php:
    - 7.0

install:
    - composer install --no-dev --quiet
    
before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-el

script:
  - ./travis-install-kafka.sh
  - phpunit -c phpunit.xml --coverage-text
