language: php

php:
    - 7.0

install:
    - composer install --no-dev --quiet
    
before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-el
  # Install Kafka
  - wget http://ftp.uk.debian.org/debian/pool/main/g/gcc-6/gcc-6-base_6.2.1-5_amd64.deb
  - wget http://ftp.uk.debian.org/debian/pool/main/g/gcc-6/libstdc++6_6.2.1-5_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/librdkafka1_0.9.1-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/librdkafka++1_0.9.1-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/librdkafka-dev_0.9.1-1_amd64.deb
  - wget http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.deb
  - wget http://mirrors.gigenet.com/apache/kafka/0.9.0.1/kafka_2.11-0.9.0.1.tgz
  - sudo dpkg -i gcc-6-base_6.2.1-5_amd64.deb
  - sudo dpkg -i libstdc++6_6.2.1-5_amd64.deb
  - sudo dpkg -i librdkafka1_0.9.1-1_amd64.deb
  - sudo dpkg -i librdkafka++1_0.9.1-1_amd64.deb
  - sudo dpkg -i librdkafka-dev_0.9.1-1_amd64.deb
  - sudo dpkg -i scala-2.11.8.deb
  - sudo apt-get -y install zookeeperd
  - tar zxf kafka_2.11-0.9.0.1.tgz

script: phpunit -c phpunit.xml --coverage-text
